export const metadata = {
  title: 'Base Project',
  description: 'Generated by Artemisa v0.3',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-white">
        {children}
      </body>
    </html>
  );
}
